import trajectory from './orbital-transfer.json';

// Generated by npm run orbit:generate. The browser only projects validated
// planar CR3BP samples and a separate frozen departure osculating ellipse.
type Point = readonly [number, number];
const earth = trajectory.bodies.earth as [number, number];
export function project(point: Point) {
  return { x: 270 + (point[0] - earth[0]) * 390, y: 460 - point[1] * 390 };
}
function point(values: number[]): Point { return [values[0]!, values[1]!]; }
const arcs = trajectory.arcs.map(arc => arc.map(point));
const projectedArcs = arcs.map(arc => arc.map(project));
function path(points: { x: number; y: number }[]) {
  return points.map((point, index) => `${index ? 'L' : 'M'}${point.x.toFixed(3)} ${point.y.toFixed(3)}`).join(' ');
}
function direction(points: { x: number; y: number }[]) {
  const lengths = [0];
  for (let index = 1; index < points.length; index++) {
    const a = points[index - 1]!, b = points[index]!;
    lengths.push(lengths[index - 1]! + Math.hypot(b.x - a.x, b.y - a.y));
  }
  const total = lengths.at(-1)!;
  const start = lengths.findIndex(length => length >= total * .45);
  const end = lengths.findIndex(length => length >= total * .50);
  return path(points.slice(start, Math.max(start + 2, end + 1)));
}
export const transferPaths = projectedArcs.map(path);
export const osculatingOrbitPath = trajectory.referenceOrbit
  ? path(trajectory.referenceOrbit.points.map(point).map(project)) : null;
export const coastDirectionPaths = projectedArcs.map(direction);
export const departure = project(trajectory.burns[0]!.position as [number, number]);
export const lunarAssist = project(trajectory.burns[1]!.position as [number, number]);
export const insertion = project(trajectory.burns[2]!.position as [number, number]);
export const coastReference = projectedArcs[0]![Math.floor(projectedArcs[0]!.length / 2)]!;
export const parkingRadius = trajectory.parkingRadius * 390;
export const earthRadius = trajectory.radii.earth * 390;
export const moonRadius = trajectory.radii.moon * 390;
export const missionMetadata = trajectory.metadata;
