/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as PortalRouteRouteImport } from './routes/portal/route'
import { Route as ApplyRouteRouteImport } from './routes/apply/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorksIndexRouteImport } from './routes/works/index'
import { Route as PortalIndexRouteImport } from './routes/portal/index'
import { Route as ApplyIndexRouteImport } from './routes/apply/index'
import { Route as WorksWorkIdRouteImport } from './routes/works/$workId'
import { Route as PortalLoginRouteImport } from './routes/portal_/login'
import { Route as PortalAdminAccessRouteImport } from './routes/portal_/admin-access'
import { Route as PortalScheduleRouteImport } from './routes/portal/schedule'
import { Route as PortalProjectRouteImport } from './routes/portal/project'
import { Route as PortalProfileRouteImport } from './routes/portal/profile'
import { Route as PortalHistoryRouteImport } from './routes/portal/history'
import { Route as PortalApplicationRouteImport } from './routes/portal/application'
import { Route as ApplySuccessRouteImport } from './routes/apply/success'
import { Route as PortalAdminRouteRouteImport } from './routes/portal_/admin/route'
import { Route as PortalAdminIndexRouteImport } from './routes/portal_/admin/index'
import { Route as PortalAdminScheduleRouteImport } from './routes/portal_/admin/schedule'
import { Route as PortalAdminProjectDraftsRouteRouteImport } from './routes/portal_/admin/project-drafts/route'
import { Route as PortalAdminParticipantsRouteRouteImport } from './routes/portal_/admin/participants/route'
import { Route as PortalAdminApplicationsRouteRouteImport } from './routes/portal_/admin/applications/route'
import { Route as PortalAdminProjectDraftsIndexRouteImport } from './routes/portal_/admin/project-drafts/index'
import { Route as PortalAdminParticipantsIndexRouteImport } from './routes/portal_/admin/participants/index'
import { Route as PortalAdminApplicationsIndexRouteImport } from './routes/portal_/admin/applications/index'
import { Route as PortalAdminSettingsWindowsRouteImport } from './routes/portal_/admin/settings/windows'
import { Route as PortalAdminSettingsAdminsRouteImport } from './routes/portal_/admin/settings/admins'
import { Route as PortalAdminProjectDraftsDraftIdRouteImport } from './routes/portal_/admin/project-drafts/$draftId'
import { Route as PortalAdminParticipantsParticipantIdRouteImport } from './routes/portal_/admin/participants/$participantId'
import { Route as PortalAdminApplicationsApplicationIdRouteImport } from './routes/portal_/admin/applications/$applicationId'

const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRouteRoute = PortalRouteRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyRouteRoute = ApplyRouteRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorksIndexRoute = WorksIndexRouteImport.update({
  id: '/works/',
  path: '/works/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRouteRoute,
} as any)
const ApplyIndexRoute = ApplyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ApplyRouteRoute,
} as any)
const WorksWorkIdRoute = WorksWorkIdRouteImport.update({
  id: '/works/$workId',
  path: '/works/$workId',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalLoginRoute = PortalLoginRouteImport.update({
  id: '/portal_/login',
  path: '/portal/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalAdminAccessRoute = PortalAdminAccessRouteImport.update({
  id: '/portal_/admin-access',
  path: '/portal/admin-access',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalScheduleRoute = PortalScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalProjectRoute = PortalProjectRouteImport.update({
  id: '/project',
  path: '/project',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalProfileRoute = PortalProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalHistoryRoute = PortalHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalApplicationRoute = PortalApplicationRouteImport.update({
  id: '/application',
  path: '/application',
  getParentRoute: () => PortalRouteRoute,
} as any)
const ApplySuccessRoute = ApplySuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => ApplyRouteRoute,
} as any)
const PortalAdminRouteRoute = PortalAdminRouteRouteImport.update({
  id: '/portal_/admin',
  path: '/portal/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalAdminIndexRoute = PortalAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalAdminRouteRoute,
} as any)
const PortalAdminScheduleRoute = PortalAdminScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => PortalAdminRouteRoute,
} as any)
const PortalAdminProjectDraftsRouteRoute =
  PortalAdminProjectDraftsRouteRouteImport.update({
    id: '/project-drafts',
    path: '/project-drafts',
    getParentRoute: () => PortalAdminRouteRoute,
  } as any)
const PortalAdminParticipantsRouteRoute =
  PortalAdminParticipantsRouteRouteImport.update({
    id: '/participants',
    path: '/participants',
    getParentRoute: () => PortalAdminRouteRoute,
  } as any)
const PortalAdminApplicationsRouteRoute =
  PortalAdminApplicationsRouteRouteImport.update({
    id: '/applications',
    path: '/applications',
    getParentRoute: () => PortalAdminRouteRoute,
  } as any)
const PortalAdminProjectDraftsIndexRoute =
  PortalAdminProjectDraftsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => PortalAdminProjectDraftsRouteRoute,
  } as any)
const PortalAdminParticipantsIndexRoute =
  PortalAdminParticipantsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => PortalAdminParticipantsRouteRoute,
  } as any)
const PortalAdminApplicationsIndexRoute =
  PortalAdminApplicationsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => PortalAdminApplicationsRouteRoute,
  } as any)
const PortalAdminSettingsWindowsRoute =
  PortalAdminSettingsWindowsRouteImport.update({
    id: '/settings/windows',
    path: '/settings/windows',
    getParentRoute: () => PortalAdminRouteRoute,
  } as any)
const PortalAdminSettingsAdminsRoute =
  PortalAdminSettingsAdminsRouteImport.update({
    id: '/settings/admins',
    path: '/settings/admins',
    getParentRoute: () => PortalAdminRouteRoute,
  } as any)
const PortalAdminProjectDraftsDraftIdRoute =
  PortalAdminProjectDraftsDraftIdRouteImport.update({
    id: '/$draftId',
    path: '/$draftId',
    getParentRoute: () => PortalAdminProjectDraftsRouteRoute,
  } as any)
const PortalAdminParticipantsParticipantIdRoute =
  PortalAdminParticipantsParticipantIdRouteImport.update({
    id: '/$participantId',
    path: '/$participantId',
    getParentRoute: () => PortalAdminParticipantsRouteRoute,
  } as any)
const PortalAdminApplicationsApplicationIdRoute =
  PortalAdminApplicationsApplicationIdRouteImport.update({
    id: '/$applicationId',
    path: '/$applicationId',
    getParentRoute: () => PortalAdminApplicationsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apply': typeof ApplyRouteRouteWithChildren
  '/portal': typeof PortalRouteRouteWithChildren
  '/rules': typeof RulesRoute
  '/portal/admin': typeof PortalAdminRouteRouteWithChildren
  '/apply/success': typeof ApplySuccessRoute
  '/portal/application': typeof PortalApplicationRoute
  '/portal/history': typeof PortalHistoryRoute
  '/portal/profile': typeof PortalProfileRoute
  '/portal/project': typeof PortalProjectRoute
  '/portal/schedule': typeof PortalScheduleRoute
  '/portal/admin-access': typeof PortalAdminAccessRoute
  '/portal/login': typeof PortalLoginRoute
  '/works/$workId': typeof WorksWorkIdRoute
  '/apply/': typeof ApplyIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/works/': typeof WorksIndexRoute
  '/portal/admin/applications': typeof PortalAdminApplicationsRouteRouteWithChildren
  '/portal/admin/participants': typeof PortalAdminParticipantsRouteRouteWithChildren
  '/portal/admin/project-drafts': typeof PortalAdminProjectDraftsRouteRouteWithChildren
  '/portal/admin/schedule': typeof PortalAdminScheduleRoute
  '/portal/admin/': typeof PortalAdminIndexRoute
  '/portal/admin/applications/$applicationId': typeof PortalAdminApplicationsApplicationIdRoute
  '/portal/admin/participants/$participantId': typeof PortalAdminParticipantsParticipantIdRoute
  '/portal/admin/project-drafts/$draftId': typeof PortalAdminProjectDraftsDraftIdRoute
  '/portal/admin/settings/admins': typeof PortalAdminSettingsAdminsRoute
  '/portal/admin/settings/windows': typeof PortalAdminSettingsWindowsRoute
  '/portal/admin/applications/': typeof PortalAdminApplicationsIndexRoute
  '/portal/admin/participants/': typeof PortalAdminParticipantsIndexRoute
  '/portal/admin/project-drafts/': typeof PortalAdminProjectDraftsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/rules': typeof RulesRoute
  '/apply/success': typeof ApplySuccessRoute
  '/portal/application': typeof PortalApplicationRoute
  '/portal/history': typeof PortalHistoryRoute
  '/portal/profile': typeof PortalProfileRoute
  '/portal/project': typeof PortalProjectRoute
  '/portal/schedule': typeof PortalScheduleRoute
  '/portal/admin-access': typeof PortalAdminAccessRoute
  '/portal/login': typeof PortalLoginRoute
  '/works/$workId': typeof WorksWorkIdRoute
  '/apply': typeof ApplyIndexRoute
  '/portal': typeof PortalIndexRoute
  '/works': typeof WorksIndexRoute
  '/portal/admin/schedule': typeof PortalAdminScheduleRoute
  '/portal/admin': typeof PortalAdminIndexRoute
  '/portal/admin/applications/$applicationId': typeof PortalAdminApplicationsApplicationIdRoute
  '/portal/admin/participants/$participantId': typeof PortalAdminParticipantsParticipantIdRoute
  '/portal/admin/project-drafts/$draftId': typeof PortalAdminProjectDraftsDraftIdRoute
  '/portal/admin/settings/admins': typeof PortalAdminSettingsAdminsRoute
  '/portal/admin/settings/windows': typeof PortalAdminSettingsWindowsRoute
  '/portal/admin/applications': typeof PortalAdminApplicationsIndexRoute
  '/portal/admin/participants': typeof PortalAdminParticipantsIndexRoute
  '/portal/admin/project-drafts': typeof PortalAdminProjectDraftsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/apply': typeof ApplyRouteRouteWithChildren
  '/portal': typeof PortalRouteRouteWithChildren
  '/rules': typeof RulesRoute
  '/portal_/admin': typeof PortalAdminRouteRouteWithChildren
  '/apply/success': typeof ApplySuccessRoute
  '/portal/application': typeof PortalApplicationRoute
  '/portal/history': typeof PortalHistoryRoute
  '/portal/profile': typeof PortalProfileRoute
  '/portal/project': typeof PortalProjectRoute
  '/portal/schedule': typeof PortalScheduleRoute
  '/portal_/admin-access': typeof PortalAdminAccessRoute
  '/portal_/login': typeof PortalLoginRoute
  '/works/$workId': typeof WorksWorkIdRoute
  '/apply/': typeof ApplyIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/works/': typeof WorksIndexRoute
  '/portal_/admin/applications': typeof PortalAdminApplicationsRouteRouteWithChildren
  '/portal_/admin/participants': typeof PortalAdminParticipantsRouteRouteWithChildren
  '/portal_/admin/project-drafts': typeof PortalAdminProjectDraftsRouteRouteWithChildren
  '/portal_/admin/schedule': typeof PortalAdminScheduleRoute
  '/portal_/admin/': typeof PortalAdminIndexRoute
  '/portal_/admin/applications/$applicationId': typeof PortalAdminApplicationsApplicationIdRoute
  '/portal_/admin/participants/$participantId': typeof PortalAdminParticipantsParticipantIdRoute
  '/portal_/admin/project-drafts/$draftId': typeof PortalAdminProjectDraftsDraftIdRoute
  '/portal_/admin/settings/admins': typeof PortalAdminSettingsAdminsRoute
  '/portal_/admin/settings/windows': typeof PortalAdminSettingsWindowsRoute
  '/portal_/admin/applications/': typeof PortalAdminApplicationsIndexRoute
  '/portal_/admin/participants/': typeof PortalAdminParticipantsIndexRoute
  '/portal_/admin/project-drafts/': typeof PortalAdminProjectDraftsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/apply'
    | '/portal'
    | '/rules'
    | '/portal/admin'
    | '/apply/success'
    | '/portal/application'
    | '/portal/history'
    | '/portal/profile'
    | '/portal/project'
    | '/portal/schedule'
    | '/portal/admin-access'
    | '/portal/login'
    | '/works/$workId'
    | '/apply/'
    | '/portal/'
    | '/works/'
    | '/portal/admin/applications'
    | '/portal/admin/participants'
    | '/portal/admin/project-drafts'
    | '/portal/admin/schedule'
    | '/portal/admin/'
    | '/portal/admin/applications/$applicationId'
    | '/portal/admin/participants/$participantId'
    | '/portal/admin/project-drafts/$draftId'
    | '/portal/admin/settings/admins'
    | '/portal/admin/settings/windows'
    | '/portal/admin/applications/'
    | '/portal/admin/participants/'
    | '/portal/admin/project-drafts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/rules'
    | '/apply/success'
    | '/portal/application'
    | '/portal/history'
    | '/portal/profile'
    | '/portal/project'
    | '/portal/schedule'
    | '/portal/admin-access'
    | '/portal/login'
    | '/works/$workId'
    | '/apply'
    | '/portal'
    | '/works'
    | '/portal/admin/schedule'
    | '/portal/admin'
    | '/portal/admin/applications/$applicationId'
    | '/portal/admin/participants/$participantId'
    | '/portal/admin/project-drafts/$draftId'
    | '/portal/admin/settings/admins'
    | '/portal/admin/settings/windows'
    | '/portal/admin/applications'
    | '/portal/admin/participants'
    | '/portal/admin/project-drafts'
  id:
    | '__root__'
    | '/'
    | '/apply'
    | '/portal'
    | '/rules'
    | '/portal_/admin'
    | '/apply/success'
    | '/portal/application'
    | '/portal/history'
    | '/portal/profile'
    | '/portal/project'
    | '/portal/schedule'
    | '/portal_/admin-access'
    | '/portal_/login'
    | '/works/$workId'
    | '/apply/'
    | '/portal/'
    | '/works/'
    | '/portal_/admin/applications'
    | '/portal_/admin/participants'
    | '/portal_/admin/project-drafts'
    | '/portal_/admin/schedule'
    | '/portal_/admin/'
    | '/portal_/admin/applications/$applicationId'
    | '/portal_/admin/participants/$participantId'
    | '/portal_/admin/project-drafts/$draftId'
    | '/portal_/admin/settings/admins'
    | '/portal_/admin/settings/windows'
    | '/portal_/admin/applications/'
    | '/portal_/admin/participants/'
    | '/portal_/admin/project-drafts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApplyRouteRoute: typeof ApplyRouteRouteWithChildren
  PortalRouteRoute: typeof PortalRouteRouteWithChildren
  RulesRoute: typeof RulesRoute
  PortalAdminRouteRoute: typeof PortalAdminRouteRouteWithChildren
  PortalAdminAccessRoute: typeof PortalAdminAccessRoute
  PortalLoginRoute: typeof PortalLoginRoute
  WorksWorkIdRoute: typeof WorksWorkIdRoute
  WorksIndexRoute: typeof WorksIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/works/': {
      id: '/works/'
      path: '/works'
      fullPath: '/works/'
      preLoaderRoute: typeof WorksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/apply/': {
      id: '/apply/'
      path: '/'
      fullPath: '/apply/'
      preLoaderRoute: typeof ApplyIndexRouteImport
      parentRoute: typeof ApplyRouteRoute
    }
    '/works/$workId': {
      id: '/works/$workId'
      path: '/works/$workId'
      fullPath: '/works/$workId'
      preLoaderRoute: typeof WorksWorkIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal_/login': {
      id: '/portal_/login'
      path: '/portal/login'
      fullPath: '/portal/login'
      preLoaderRoute: typeof PortalLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal_/admin-access': {
      id: '/portal_/admin-access'
      path: '/portal/admin-access'
      fullPath: '/portal/admin-access'
      preLoaderRoute: typeof PortalAdminAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/schedule': {
      id: '/portal/schedule'
      path: '/schedule'
      fullPath: '/portal/schedule'
      preLoaderRoute: typeof PortalScheduleRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/project': {
      id: '/portal/project'
      path: '/project'
      fullPath: '/portal/project'
      preLoaderRoute: typeof PortalProjectRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/profile': {
      id: '/portal/profile'
      path: '/profile'
      fullPath: '/portal/profile'
      preLoaderRoute: typeof PortalProfileRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/history': {
      id: '/portal/history'
      path: '/history'
      fullPath: '/portal/history'
      preLoaderRoute: typeof PortalHistoryRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/application': {
      id: '/portal/application'
      path: '/application'
      fullPath: '/portal/application'
      preLoaderRoute: typeof PortalApplicationRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/apply/success': {
      id: '/apply/success'
      path: '/success'
      fullPath: '/apply/success'
      preLoaderRoute: typeof ApplySuccessRouteImport
      parentRoute: typeof ApplyRouteRoute
    }
    '/portal_/admin': {
      id: '/portal_/admin'
      path: '/portal/admin'
      fullPath: '/portal/admin'
      preLoaderRoute: typeof PortalAdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal_/admin/': {
      id: '/portal_/admin/'
      path: '/'
      fullPath: '/portal/admin/'
      preLoaderRoute: typeof PortalAdminIndexRouteImport
      parentRoute: typeof PortalAdminRouteRoute
    }
    '/portal_/admin/schedule': {
      id: '/portal_/admin/schedule'
      path: '/schedule'
      fullPath: '/portal/admin/schedule'
      preLoaderRoute: typeof PortalAdminScheduleRouteImport
      parentRoute: typeof PortalAdminRouteRoute
    }
    '/portal_/admin/project-drafts': {
      id: '/portal_/admin/project-drafts'
      path: '/project-drafts'
      fullPath: '/portal/admin/project-drafts'
      preLoaderRoute: typeof PortalAdminProjectDraftsRouteRouteImport
      parentRoute: typeof PortalAdminRouteRoute
    }
    '/portal_/admin/participants': {
      id: '/portal_/admin/participants'
      path: '/participants'
      fullPath: '/portal/admin/participants'
      preLoaderRoute: typeof PortalAdminParticipantsRouteRouteImport
      parentRoute: typeof PortalAdminRouteRoute
    }
    '/portal_/admin/applications': {
      id: '/portal_/admin/applications'
      path: '/applications'
      fullPath: '/portal/admin/applications'
      preLoaderRoute: typeof PortalAdminApplicationsRouteRouteImport
      parentRoute: typeof PortalAdminRouteRoute
    }
    '/portal_/admin/project-drafts/': {
      id: '/portal_/admin/project-drafts/'
      path: '/'
      fullPath: '/portal/admin/project-drafts/'
      preLoaderRoute: typeof PortalAdminProjectDraftsIndexRouteImport
      parentRoute: typeof PortalAdminProjectDraftsRouteRoute
    }
    '/portal_/admin/participants/': {
      id: '/portal_/admin/participants/'
      path: '/'
      fullPath: '/portal/admin/participants/'
      preLoaderRoute: typeof PortalAdminParticipantsIndexRouteImport
      parentRoute: typeof PortalAdminParticipantsRouteRoute
    }
    '/portal_/admin/applications/': {
      id: '/portal_/admin/applications/'
      path: '/'
      fullPath: '/portal/admin/applications/'
      preLoaderRoute: typeof PortalAdminApplicationsIndexRouteImport
      parentRoute: typeof PortalAdminApplicationsRouteRoute
    }
    '/portal_/admin/settings/windows': {
      id: '/portal_/admin/settings/windows'
      path: '/settings/windows'
      fullPath: '/portal/admin/settings/windows'
      preLoaderRoute: typeof PortalAdminSettingsWindowsRouteImport
      parentRoute: typeof PortalAdminRouteRoute
    }
    '/portal_/admin/settings/admins': {
      id: '/portal_/admin/settings/admins'
      path: '/settings/admins'
      fullPath: '/portal/admin/settings/admins'
      preLoaderRoute: typeof PortalAdminSettingsAdminsRouteImport
      parentRoute: typeof PortalAdminRouteRoute
    }
    '/portal_/admin/project-drafts/$draftId': {
      id: '/portal_/admin/project-drafts/$draftId'
      path: '/$draftId'
      fullPath: '/portal/admin/project-drafts/$draftId'
      preLoaderRoute: typeof PortalAdminProjectDraftsDraftIdRouteImport
      parentRoute: typeof PortalAdminProjectDraftsRouteRoute
    }
    '/portal_/admin/participants/$participantId': {
      id: '/portal_/admin/participants/$participantId'
      path: '/$participantId'
      fullPath: '/portal/admin/participants/$participantId'
      preLoaderRoute: typeof PortalAdminParticipantsParticipantIdRouteImport
      parentRoute: typeof PortalAdminParticipantsRouteRoute
    }
    '/portal_/admin/applications/$applicationId': {
      id: '/portal_/admin/applications/$applicationId'
      path: '/$applicationId'
      fullPath: '/portal/admin/applications/$applicationId'
      preLoaderRoute: typeof PortalAdminApplicationsApplicationIdRouteImport
      parentRoute: typeof PortalAdminApplicationsRouteRoute
    }
  }
}

interface ApplyRouteRouteChildren {
  ApplySuccessRoute: typeof ApplySuccessRoute
  ApplyIndexRoute: typeof ApplyIndexRoute
}

const ApplyRouteRouteChildren: ApplyRouteRouteChildren = {
  ApplySuccessRoute: ApplySuccessRoute,
  ApplyIndexRoute: ApplyIndexRoute,
}

const ApplyRouteRouteWithChildren = ApplyRouteRoute._addFileChildren(
  ApplyRouteRouteChildren,
)

interface PortalRouteRouteChildren {
  PortalApplicationRoute: typeof PortalApplicationRoute
  PortalHistoryRoute: typeof PortalHistoryRoute
  PortalProfileRoute: typeof PortalProfileRoute
  PortalProjectRoute: typeof PortalProjectRoute
  PortalScheduleRoute: typeof PortalScheduleRoute
  PortalIndexRoute: typeof PortalIndexRoute
}

const PortalRouteRouteChildren: PortalRouteRouteChildren = {
  PortalApplicationRoute: PortalApplicationRoute,
  PortalHistoryRoute: PortalHistoryRoute,
  PortalProfileRoute: PortalProfileRoute,
  PortalProjectRoute: PortalProjectRoute,
  PortalScheduleRoute: PortalScheduleRoute,
  PortalIndexRoute: PortalIndexRoute,
}

const PortalRouteRouteWithChildren = PortalRouteRoute._addFileChildren(
  PortalRouteRouteChildren,
)

interface PortalAdminApplicationsRouteRouteChildren {
  PortalAdminApplicationsApplicationIdRoute: typeof PortalAdminApplicationsApplicationIdRoute
  PortalAdminApplicationsIndexRoute: typeof PortalAdminApplicationsIndexRoute
}

const PortalAdminApplicationsRouteRouteChildren: PortalAdminApplicationsRouteRouteChildren =
  {
    PortalAdminApplicationsApplicationIdRoute:
      PortalAdminApplicationsApplicationIdRoute,
    PortalAdminApplicationsIndexRoute: PortalAdminApplicationsIndexRoute,
  }

const PortalAdminApplicationsRouteRouteWithChildren =
  PortalAdminApplicationsRouteRoute._addFileChildren(
    PortalAdminApplicationsRouteRouteChildren,
  )

interface PortalAdminParticipantsRouteRouteChildren {
  PortalAdminParticipantsParticipantIdRoute: typeof PortalAdminParticipantsParticipantIdRoute
  PortalAdminParticipantsIndexRoute: typeof PortalAdminParticipantsIndexRoute
}

const PortalAdminParticipantsRouteRouteChildren: PortalAdminParticipantsRouteRouteChildren =
  {
    PortalAdminParticipantsParticipantIdRoute:
      PortalAdminParticipantsParticipantIdRoute,
    PortalAdminParticipantsIndexRoute: PortalAdminParticipantsIndexRoute,
  }

const PortalAdminParticipantsRouteRouteWithChildren =
  PortalAdminParticipantsRouteRoute._addFileChildren(
    PortalAdminParticipantsRouteRouteChildren,
  )

interface PortalAdminProjectDraftsRouteRouteChildren {
  PortalAdminProjectDraftsDraftIdRoute: typeof PortalAdminProjectDraftsDraftIdRoute
  PortalAdminProjectDraftsIndexRoute: typeof PortalAdminProjectDraftsIndexRoute
}

const PortalAdminProjectDraftsRouteRouteChildren: PortalAdminProjectDraftsRouteRouteChildren =
  {
    PortalAdminProjectDraftsDraftIdRoute: PortalAdminProjectDraftsDraftIdRoute,
    PortalAdminProjectDraftsIndexRoute: PortalAdminProjectDraftsIndexRoute,
  }

const PortalAdminProjectDraftsRouteRouteWithChildren =
  PortalAdminProjectDraftsRouteRoute._addFileChildren(
    PortalAdminProjectDraftsRouteRouteChildren,
  )

interface PortalAdminRouteRouteChildren {
  PortalAdminApplicationsRouteRoute: typeof PortalAdminApplicationsRouteRouteWithChildren
  PortalAdminParticipantsRouteRoute: typeof PortalAdminParticipantsRouteRouteWithChildren
  PortalAdminProjectDraftsRouteRoute: typeof PortalAdminProjectDraftsRouteRouteWithChildren
  PortalAdminScheduleRoute: typeof PortalAdminScheduleRoute
  PortalAdminIndexRoute: typeof PortalAdminIndexRoute
  PortalAdminSettingsAdminsRoute: typeof PortalAdminSettingsAdminsRoute
  PortalAdminSettingsWindowsRoute: typeof PortalAdminSettingsWindowsRoute
}

const PortalAdminRouteRouteChildren: PortalAdminRouteRouteChildren = {
  PortalAdminApplicationsRouteRoute:
    PortalAdminApplicationsRouteRouteWithChildren,
  PortalAdminParticipantsRouteRoute:
    PortalAdminParticipantsRouteRouteWithChildren,
  PortalAdminProjectDraftsRouteRoute:
    PortalAdminProjectDraftsRouteRouteWithChildren,
  PortalAdminScheduleRoute: PortalAdminScheduleRoute,
  PortalAdminIndexRoute: PortalAdminIndexRoute,
  PortalAdminSettingsAdminsRoute: PortalAdminSettingsAdminsRoute,
  PortalAdminSettingsWindowsRoute: PortalAdminSettingsWindowsRoute,
}

const PortalAdminRouteRouteWithChildren =
  PortalAdminRouteRoute._addFileChildren(PortalAdminRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApplyRouteRoute: ApplyRouteRouteWithChildren,
  PortalRouteRoute: PortalRouteRouteWithChildren,
  RulesRoute: RulesRoute,
  PortalAdminRouteRoute: PortalAdminRouteRouteWithChildren,
  PortalAdminAccessRoute: PortalAdminAccessRoute,
  PortalLoginRoute: PortalLoginRoute,
  WorksWorkIdRoute: WorksWorkIdRoute,
  WorksIndexRoute: WorksIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
