/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PortalRouteRouteImport } from './routes/portal/route'
import { Route as ApplyRouteRouteImport } from './routes/apply/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortalIndexRouteImport } from './routes/portal/index'
import { Route as ApplyIndexRouteImport } from './routes/apply/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as PortalLoginRouteImport } from './routes/portal_/login'
import { Route as PortalScheduleRouteImport } from './routes/portal/schedule'
import { Route as PortalProjectRouteImport } from './routes/portal/project'
import { Route as PortalProfileRouteImport } from './routes/portal/profile'
import { Route as PortalHistoryRouteImport } from './routes/portal/history'
import { Route as PortalApplicationRouteImport } from './routes/portal/application'
import { Route as ApplySuccessRouteImport } from './routes/apply/success'
import { Route as AdminScheduleRouteImport } from './routes/admin/schedule'
import { Route as AdminProjectDraftsRouteRouteImport } from './routes/admin/project-drafts/route'
import { Route as AdminParticipantsRouteRouteImport } from './routes/admin/participants/route'
import { Route as AdminApplicationsRouteRouteImport } from './routes/admin/applications/route'
import { Route as AdminProjectDraftsIndexRouteImport } from './routes/admin/project-drafts/index'
import { Route as AdminParticipantsIndexRouteImport } from './routes/admin/participants/index'
import { Route as AdminApplicationsIndexRouteImport } from './routes/admin/applications/index'
import { Route as AdminSettingsWindowsRouteImport } from './routes/admin/settings/windows'
import { Route as AdminProjectDraftsDraftIdRouteImport } from './routes/admin/project-drafts/$draftId'
import { Route as AdminParticipantsParticipantIdRouteImport } from './routes/admin/participants/$participantId'
import { Route as AdminApplicationsApplicationIdRouteImport } from './routes/admin/applications/$applicationId'

const PortalRouteRoute = PortalRouteRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyRouteRoute = ApplyRouteRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRouteRoute,
} as any)
const ApplyIndexRoute = ApplyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ApplyRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const PortalLoginRoute = PortalLoginRouteImport.update({
  id: '/portal_/login',
  path: '/portal/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalScheduleRoute = PortalScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalProjectRoute = PortalProjectRouteImport.update({
  id: '/project',
  path: '/project',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalProfileRoute = PortalProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalHistoryRoute = PortalHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalApplicationRoute = PortalApplicationRouteImport.update({
  id: '/application',
  path: '/application',
  getParentRoute: () => PortalRouteRoute,
} as any)
const ApplySuccessRoute = ApplySuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => ApplyRouteRoute,
} as any)
const AdminScheduleRoute = AdminScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProjectDraftsRouteRoute = AdminProjectDraftsRouteRouteImport.update({
  id: '/project-drafts',
  path: '/project-drafts',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminParticipantsRouteRoute = AdminParticipantsRouteRouteImport.update({
  id: '/participants',
  path: '/participants',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminApplicationsRouteRoute = AdminApplicationsRouteRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProjectDraftsIndexRoute = AdminProjectDraftsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminProjectDraftsRouteRoute,
} as any)
const AdminParticipantsIndexRoute = AdminParticipantsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminParticipantsRouteRoute,
} as any)
const AdminApplicationsIndexRoute = AdminApplicationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminApplicationsRouteRoute,
} as any)
const AdminSettingsWindowsRoute = AdminSettingsWindowsRouteImport.update({
  id: '/settings/windows',
  path: '/settings/windows',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProjectDraftsDraftIdRoute =
  AdminProjectDraftsDraftIdRouteImport.update({
    id: '/$draftId',
    path: '/$draftId',
    getParentRoute: () => AdminProjectDraftsRouteRoute,
  } as any)
const AdminParticipantsParticipantIdRoute =
  AdminParticipantsParticipantIdRouteImport.update({
    id: '/$participantId',
    path: '/$participantId',
    getParentRoute: () => AdminParticipantsRouteRoute,
  } as any)
const AdminApplicationsApplicationIdRoute =
  AdminApplicationsApplicationIdRouteImport.update({
    id: '/$applicationId',
    path: '/$applicationId',
    getParentRoute: () => AdminApplicationsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/apply': typeof ApplyRouteRouteWithChildren
  '/portal': typeof PortalRouteRouteWithChildren
  '/admin/applications': typeof AdminApplicationsRouteRouteWithChildren
  '/admin/participants': typeof AdminParticipantsRouteRouteWithChildren
  '/admin/project-drafts': typeof AdminProjectDraftsRouteRouteWithChildren
  '/admin/schedule': typeof AdminScheduleRoute
  '/apply/success': typeof ApplySuccessRoute
  '/portal/application': typeof PortalApplicationRoute
  '/portal/history': typeof PortalHistoryRoute
  '/portal/profile': typeof PortalProfileRoute
  '/portal/project': typeof PortalProjectRoute
  '/portal/schedule': typeof PortalScheduleRoute
  '/portal/login': typeof PortalLoginRoute
  '/admin/': typeof AdminIndexRoute
  '/apply/': typeof ApplyIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/admin/applications/$applicationId': typeof AdminApplicationsApplicationIdRoute
  '/admin/participants/$participantId': typeof AdminParticipantsParticipantIdRoute
  '/admin/project-drafts/$draftId': typeof AdminProjectDraftsDraftIdRoute
  '/admin/settings/windows': typeof AdminSettingsWindowsRoute
  '/admin/applications/': typeof AdminApplicationsIndexRoute
  '/admin/participants/': typeof AdminParticipantsIndexRoute
  '/admin/project-drafts/': typeof AdminProjectDraftsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/schedule': typeof AdminScheduleRoute
  '/apply/success': typeof ApplySuccessRoute
  '/portal/application': typeof PortalApplicationRoute
  '/portal/history': typeof PortalHistoryRoute
  '/portal/profile': typeof PortalProfileRoute
  '/portal/project': typeof PortalProjectRoute
  '/portal/schedule': typeof PortalScheduleRoute
  '/portal/login': typeof PortalLoginRoute
  '/admin': typeof AdminIndexRoute
  '/apply': typeof ApplyIndexRoute
  '/portal': typeof PortalIndexRoute
  '/admin/applications/$applicationId': typeof AdminApplicationsApplicationIdRoute
  '/admin/participants/$participantId': typeof AdminParticipantsParticipantIdRoute
  '/admin/project-drafts/$draftId': typeof AdminProjectDraftsDraftIdRoute
  '/admin/settings/windows': typeof AdminSettingsWindowsRoute
  '/admin/applications': typeof AdminApplicationsIndexRoute
  '/admin/participants': typeof AdminParticipantsIndexRoute
  '/admin/project-drafts': typeof AdminProjectDraftsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/apply': typeof ApplyRouteRouteWithChildren
  '/portal': typeof PortalRouteRouteWithChildren
  '/admin/applications': typeof AdminApplicationsRouteRouteWithChildren
  '/admin/participants': typeof AdminParticipantsRouteRouteWithChildren
  '/admin/project-drafts': typeof AdminProjectDraftsRouteRouteWithChildren
  '/admin/schedule': typeof AdminScheduleRoute
  '/apply/success': typeof ApplySuccessRoute
  '/portal/application': typeof PortalApplicationRoute
  '/portal/history': typeof PortalHistoryRoute
  '/portal/profile': typeof PortalProfileRoute
  '/portal/project': typeof PortalProjectRoute
  '/portal/schedule': typeof PortalScheduleRoute
  '/portal_/login': typeof PortalLoginRoute
  '/admin/': typeof AdminIndexRoute
  '/apply/': typeof ApplyIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/admin/applications/$applicationId': typeof AdminApplicationsApplicationIdRoute
  '/admin/participants/$participantId': typeof AdminParticipantsParticipantIdRoute
  '/admin/project-drafts/$draftId': typeof AdminProjectDraftsDraftIdRoute
  '/admin/settings/windows': typeof AdminSettingsWindowsRoute
  '/admin/applications/': typeof AdminApplicationsIndexRoute
  '/admin/participants/': typeof AdminParticipantsIndexRoute
  '/admin/project-drafts/': typeof AdminProjectDraftsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/apply'
    | '/portal'
    | '/admin/applications'
    | '/admin/participants'
    | '/admin/project-drafts'
    | '/admin/schedule'
    | '/apply/success'
    | '/portal/application'
    | '/portal/history'
    | '/portal/profile'
    | '/portal/project'
    | '/portal/schedule'
    | '/portal/login'
    | '/admin/'
    | '/apply/'
    | '/portal/'
    | '/admin/applications/$applicationId'
    | '/admin/participants/$participantId'
    | '/admin/project-drafts/$draftId'
    | '/admin/settings/windows'
    | '/admin/applications/'
    | '/admin/participants/'
    | '/admin/project-drafts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/schedule'
    | '/apply/success'
    | '/portal/application'
    | '/portal/history'
    | '/portal/profile'
    | '/portal/project'
    | '/portal/schedule'
    | '/portal/login'
    | '/admin'
    | '/apply'
    | '/portal'
    | '/admin/applications/$applicationId'
    | '/admin/participants/$participantId'
    | '/admin/project-drafts/$draftId'
    | '/admin/settings/windows'
    | '/admin/applications'
    | '/admin/participants'
    | '/admin/project-drafts'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/apply'
    | '/portal'
    | '/admin/applications'
    | '/admin/participants'
    | '/admin/project-drafts'
    | '/admin/schedule'
    | '/apply/success'
    | '/portal/application'
    | '/portal/history'
    | '/portal/profile'
    | '/portal/project'
    | '/portal/schedule'
    | '/portal_/login'
    | '/admin/'
    | '/apply/'
    | '/portal/'
    | '/admin/applications/$applicationId'
    | '/admin/participants/$participantId'
    | '/admin/project-drafts/$draftId'
    | '/admin/settings/windows'
    | '/admin/applications/'
    | '/admin/participants/'
    | '/admin/project-drafts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  ApplyRouteRoute: typeof ApplyRouteRouteWithChildren
  PortalRouteRoute: typeof PortalRouteRouteWithChildren
  PortalLoginRoute: typeof PortalLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/apply/': {
      id: '/apply/'
      path: '/'
      fullPath: '/apply/'
      preLoaderRoute: typeof ApplyIndexRouteImport
      parentRoute: typeof ApplyRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/portal_/login': {
      id: '/portal_/login'
      path: '/portal/login'
      fullPath: '/portal/login'
      preLoaderRoute: typeof PortalLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/schedule': {
      id: '/portal/schedule'
      path: '/schedule'
      fullPath: '/portal/schedule'
      preLoaderRoute: typeof PortalScheduleRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/project': {
      id: '/portal/project'
      path: '/project'
      fullPath: '/portal/project'
      preLoaderRoute: typeof PortalProjectRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/profile': {
      id: '/portal/profile'
      path: '/profile'
      fullPath: '/portal/profile'
      preLoaderRoute: typeof PortalProfileRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/history': {
      id: '/portal/history'
      path: '/history'
      fullPath: '/portal/history'
      preLoaderRoute: typeof PortalHistoryRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/application': {
      id: '/portal/application'
      path: '/application'
      fullPath: '/portal/application'
      preLoaderRoute: typeof PortalApplicationRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/apply/success': {
      id: '/apply/success'
      path: '/success'
      fullPath: '/apply/success'
      preLoaderRoute: typeof ApplySuccessRouteImport
      parentRoute: typeof ApplyRouteRoute
    }
    '/admin/schedule': {
      id: '/admin/schedule'
      path: '/schedule'
      fullPath: '/admin/schedule'
      preLoaderRoute: typeof AdminScheduleRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/project-drafts': {
      id: '/admin/project-drafts'
      path: '/project-drafts'
      fullPath: '/admin/project-drafts'
      preLoaderRoute: typeof AdminProjectDraftsRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/participants': {
      id: '/admin/participants'
      path: '/participants'
      fullPath: '/admin/participants'
      preLoaderRoute: typeof AdminParticipantsRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/applications': {
      id: '/admin/applications'
      path: '/applications'
      fullPath: '/admin/applications'
      preLoaderRoute: typeof AdminApplicationsRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/project-drafts/': {
      id: '/admin/project-drafts/'
      path: '/'
      fullPath: '/admin/project-drafts/'
      preLoaderRoute: typeof AdminProjectDraftsIndexRouteImport
      parentRoute: typeof AdminProjectDraftsRouteRoute
    }
    '/admin/participants/': {
      id: '/admin/participants/'
      path: '/'
      fullPath: '/admin/participants/'
      preLoaderRoute: typeof AdminParticipantsIndexRouteImport
      parentRoute: typeof AdminParticipantsRouteRoute
    }
    '/admin/applications/': {
      id: '/admin/applications/'
      path: '/'
      fullPath: '/admin/applications/'
      preLoaderRoute: typeof AdminApplicationsIndexRouteImport
      parentRoute: typeof AdminApplicationsRouteRoute
    }
    '/admin/settings/windows': {
      id: '/admin/settings/windows'
      path: '/settings/windows'
      fullPath: '/admin/settings/windows'
      preLoaderRoute: typeof AdminSettingsWindowsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/project-drafts/$draftId': {
      id: '/admin/project-drafts/$draftId'
      path: '/$draftId'
      fullPath: '/admin/project-drafts/$draftId'
      preLoaderRoute: typeof AdminProjectDraftsDraftIdRouteImport
      parentRoute: typeof AdminProjectDraftsRouteRoute
    }
    '/admin/participants/$participantId': {
      id: '/admin/participants/$participantId'
      path: '/$participantId'
      fullPath: '/admin/participants/$participantId'
      preLoaderRoute: typeof AdminParticipantsParticipantIdRouteImport
      parentRoute: typeof AdminParticipantsRouteRoute
    }
    '/admin/applications/$applicationId': {
      id: '/admin/applications/$applicationId'
      path: '/$applicationId'
      fullPath: '/admin/applications/$applicationId'
      preLoaderRoute: typeof AdminApplicationsApplicationIdRouteImport
      parentRoute: typeof AdminApplicationsRouteRoute
    }
  }
}

interface AdminApplicationsRouteRouteChildren {
  AdminApplicationsApplicationIdRoute: typeof AdminApplicationsApplicationIdRoute
  AdminApplicationsIndexRoute: typeof AdminApplicationsIndexRoute
}

const AdminApplicationsRouteRouteChildren: AdminApplicationsRouteRouteChildren =
  {
    AdminApplicationsApplicationIdRoute: AdminApplicationsApplicationIdRoute,
    AdminApplicationsIndexRoute: AdminApplicationsIndexRoute,
  }

const AdminApplicationsRouteRouteWithChildren =
  AdminApplicationsRouteRoute._addFileChildren(
    AdminApplicationsRouteRouteChildren,
  )

interface AdminParticipantsRouteRouteChildren {
  AdminParticipantsParticipantIdRoute: typeof AdminParticipantsParticipantIdRoute
  AdminParticipantsIndexRoute: typeof AdminParticipantsIndexRoute
}

const AdminParticipantsRouteRouteChildren: AdminParticipantsRouteRouteChildren =
  {
    AdminParticipantsParticipantIdRoute: AdminParticipantsParticipantIdRoute,
    AdminParticipantsIndexRoute: AdminParticipantsIndexRoute,
  }

const AdminParticipantsRouteRouteWithChildren =
  AdminParticipantsRouteRoute._addFileChildren(
    AdminParticipantsRouteRouteChildren,
  )

interface AdminProjectDraftsRouteRouteChildren {
  AdminProjectDraftsDraftIdRoute: typeof AdminProjectDraftsDraftIdRoute
  AdminProjectDraftsIndexRoute: typeof AdminProjectDraftsIndexRoute
}

const AdminProjectDraftsRouteRouteChildren: AdminProjectDraftsRouteRouteChildren =
  {
    AdminProjectDraftsDraftIdRoute: AdminProjectDraftsDraftIdRoute,
    AdminProjectDraftsIndexRoute: AdminProjectDraftsIndexRoute,
  }

const AdminProjectDraftsRouteRouteWithChildren =
  AdminProjectDraftsRouteRoute._addFileChildren(
    AdminProjectDraftsRouteRouteChildren,
  )

interface AdminRouteRouteChildren {
  AdminApplicationsRouteRoute: typeof AdminApplicationsRouteRouteWithChildren
  AdminParticipantsRouteRoute: typeof AdminParticipantsRouteRouteWithChildren
  AdminProjectDraftsRouteRoute: typeof AdminProjectDraftsRouteRouteWithChildren
  AdminScheduleRoute: typeof AdminScheduleRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminSettingsWindowsRoute: typeof AdminSettingsWindowsRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminApplicationsRouteRoute: AdminApplicationsRouteRouteWithChildren,
  AdminParticipantsRouteRoute: AdminParticipantsRouteRouteWithChildren,
  AdminProjectDraftsRouteRoute: AdminProjectDraftsRouteRouteWithChildren,
  AdminScheduleRoute: AdminScheduleRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminSettingsWindowsRoute: AdminSettingsWindowsRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface ApplyRouteRouteChildren {
  ApplySuccessRoute: typeof ApplySuccessRoute
  ApplyIndexRoute: typeof ApplyIndexRoute
}

const ApplyRouteRouteChildren: ApplyRouteRouteChildren = {
  ApplySuccessRoute: ApplySuccessRoute,
  ApplyIndexRoute: ApplyIndexRoute,
}

const ApplyRouteRouteWithChildren = ApplyRouteRoute._addFileChildren(
  ApplyRouteRouteChildren,
)

interface PortalRouteRouteChildren {
  PortalApplicationRoute: typeof PortalApplicationRoute
  PortalHistoryRoute: typeof PortalHistoryRoute
  PortalProfileRoute: typeof PortalProfileRoute
  PortalProjectRoute: typeof PortalProjectRoute
  PortalScheduleRoute: typeof PortalScheduleRoute
  PortalIndexRoute: typeof PortalIndexRoute
}

const PortalRouteRouteChildren: PortalRouteRouteChildren = {
  PortalApplicationRoute: PortalApplicationRoute,
  PortalHistoryRoute: PortalHistoryRoute,
  PortalProfileRoute: PortalProfileRoute,
  PortalProjectRoute: PortalProjectRoute,
  PortalScheduleRoute: PortalScheduleRoute,
  PortalIndexRoute: PortalIndexRoute,
}

const PortalRouteRouteWithChildren = PortalRouteRoute._addFileChildren(
  PortalRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  ApplyRouteRoute: ApplyRouteRouteWithChildren,
  PortalRouteRoute: PortalRouteRouteWithChildren,
  PortalLoginRoute: PortalLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
